# Spring
spring:
    application:
    name: st2-exam

    # Hibernate ddl auto
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                event:
                    merge:
                        entity_copy_observer: allow
# Server
server:
    port: 8080
    compression.enabled: true
    compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain
